site_name: Посібник користувача ESS Monitor Tool
site_dir: public
copyright: |
    © 2024 OVA Studio
    All rights reserved.
nav:
  - index.md

theme:
  name: material
  language: uk
  logo: assets/images/logo-white.png
  favicon: assets/images/favicon.svg
extra:
  generator: false